### PR TITLE
Store state as byte[] together with task instance. #5

### PR DESCRIPTION
**Pull request by tedsteen**
Alternate suggestion for #5 using byte[] as state instead of String

### CODE REVIEW

**Comment by kagkarlsson** [comment]
A few comments, up for discussion if you disagree :)

* I feel maybe `data` is a better term than `state`, `state` almost implies that it will change over time (for field-name and column-name)
* The `withState(...)` is perhaps unnecessary if there is a constructor taking a state-argument
* `byte[]` feels slightly more honest/clear, InputStream might leave some questions like "is it lazy?", and String is not a natural type to keep "data" in. However, it might be a good idea to look into creating a new type of `Task` that does serialization and is "type-safe".

**Comment by tedsteen** [comment]
>I feel maybe data is a better term than state, state almost implies that it will change over time (for field-name and column-name)

Agreed!

>The withState(...) is perhaps unnecessary if there is a constructor taking a state-argument

This crossed my mind as well. Will amend.

>byte[] feels slightly more honest/clear, InputStream might leave some questions like "is it lazy?", and String is not a natural type to keep "data" in.

Agree here as well, it's def more honest with byte[].

>However, it might be a good idea to look into creating a new type of Task that does serialization and is "type-safe".

This sounds like an interesting idea, will give it a shot!

**Comment by tedsteen** [comment]
Did amendments for the points you brought up. The last point I did in a separate PR

**Comment by kagkarlsson** [comment]
Looks good. I think this PR can be merged :)

**Comment by tedsteen** [comment]
Cool, this one or the one with the type information on the task instance? (#9)

**Comment by kagkarlsson** [comment]
See comment in #9 , I think we can do the type-safe task in a separate PR

**Pull request merged**
