### PR TITLE
add mssql table definition

### PR DESCRIPTION
**Pull request by krismorte**
I started to study the code and in my first test I was able to execute in MSSQL.
By the way the word version is reserved in MSSQL, my suggestion is that in the future it will be changed.

In the future I intend to contribute more, thanks!

### CODE REVIEW

**Comment by kagkarlsson** [comment]
Thank you for the pull request! Could you run the `CompatibilityTest` against a database you have created with this schema? You probably have to add a msql jdbc-driver and create something similar to `com.github.kagkarlsson.scheduler.compatibility.OracleCompatibilityTest`.

There has also been some discussion regarding mssql schema here: #21

**Comment by krismorte** [comment]
Ok, I read the issue and make some changes based on it. I also add the MssqlCompatibilityTest and MssqlTestDatabaseRule. You can drop this PR I will send another with the changes.

**Comment by kagkarlsson** [comment]
Ok, great!

Btw, it looks like you have some auto-formatting going on. I would appreciate not getting any lines with only whitespace-change in the PR :)

**Comment by krismorte** [comment]
Ok, but how can I fix this?
If I send another commit the blank line will going off?

**Comment by kagkarlsson** [comment]
Yeah, if you revert the whitespace changes in this branch and commit, it will disappear from the changes here in the PR. 

Or you can do something like this (though in your case, a bit further than `HEAD~1`):
http://blog.ranjansakalley.com/2015/09/cleaning-up-whitespace-changes-in-a-pull-request.html

The simplest thing is perhaps to create a new branch and manually add the actual changes again. Be sure to disable auto-format on save in your IDE.

**Pull request closed without merging**
