### PR TITLE
fix: Replace TOC link with the correct item `Third-party extensions`

### PR DESCRIPTION
**Pull request by dimio**
## Brief, plain english overview of your changes here
Replace TOC link with the correct item `Third-party extensions`.

## Fixes
No `#issue`. This fix is ​​not worth discussing.

## Reminders
- [ ] Added/ran automated tests
- [x] Update README and/or examples
- [ ] Ran `mvn spotless:apply`

---
cc @kagkarlsson

### CODE REVIEW

**Review by kagkarlsson — APPROVED** [review]
Thank you for fixing! 🙏

**Comment by dimio** [comment]
@kagkarlsson
Thank you for nice scheduler :)
I must close this PR or?

**Comment by kagkarlsson** [comment]
I forgot to merge :)

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v14.1.0` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v14.1.0))

**Pull request merged**
