### PR TITLE
Typesafe task state

### PR DESCRIPTION
**Pull request by tedsteen**
An iteration of #8 where state now has a type and serialization/deserialization happens before reading/writing to db.

### CODE REVIEW

**Comment by kagkarlsson** [comment]
I was thinking more in lines of creating a subclass of OneTimeTask, say `OneTimeTaskWithData` which has another signature for the `execute` method, and that the serialization is taken care of in `OneTimeTaskWithData`, in the `execute(TaskInstance taskInstance, ExecutionContext executionContext)` method, delegating to a new `execute` method.

Sorry for not being more clear. I am very excited about your additions, but struggle with finding time to follow up. Working on it though! :)

**Comment by tedsteen** [comment]
>I was thinking more in lines of creating a subclass of OneTimeTask, say OneTimeTaskWithData which has another signature for the execute method, and that the serialization is taken care of in OneTimeTaskWithData, in the execute(TaskInstance taskInstance, ExecutionContext executionContext) method, delegating to a new execute method.

I see, will have a stab at it.

>Sorry for not being more clear.

No worries! It's probably quite similar to what I've done already, just some refactoring :)

>I am very excited about your additions, but struggle with finding time to follow up. Working on it though! :)

Again no worries :)

**Comment by kagkarlsson** [comment]
Yeah, but it is not touching the JdbcTaskRepository class, so should be a more isolated change, just the `Seeializer` classes and a new task I think

**Comment by kagkarlsson** [comment]
Can I close this PR?

**Pull request closed without merging**
