### PR TITLE
Add @ConditionalOnEnabledHealthIndicator

### PR DESCRIPTION
**Pull request by ystarikovich**
To follow Spring best practices and give a possibility to disable/enable health indicator @ConditionalOnEnabledHealthIndicator was introduced

### CODE REVIEW

**Comment by kagkarlsson** [comment]
Excellent! I am unfortunately not very familiar with Spring Boot best practices, can I find them somewhere?

So with this change you have to "opt-in" to get a `HealthIndicator`? 
Are `HealthIndicators` primarily used to indicate the healthiness of the application, i.e. if it should receive traffic?

**Comment by ystarikovich** [comment]
I made a link to the spring documentation, there is information how HealthIndicators are living in the Spring ecosystem and also how anyone can configure behaviour of particular indicator or all indicators in general.

There is no possibility to control this HealthCheck behaviour right now. From perspective of our application and maybe someone else will have the same problem, db-scheduler availability should not be a indicator for container orchestration framework to kill instance of application as this is non critical part and application should receive traffic if something happened with db-scheduler.

**Comment by kagkarlsson** [comment]
I agree that if the `HealthIndicator` is used to signal the health/readiness of the application it should default to off, since db-scheduler is really a sort of independent sub-system living in the same JVM. We can serve user-traffic without it.

**Comment by kagkarlsson** [comment]
Let me know if you need a release with this fix.

**Comment by ystarikovich** [comment]
Would appreciate if you can release this as right now we are using workaround for this.

**Comment by kagkarlsson** [comment]
Np. Release 6.6 should be available in central now 👍

**Pull request merged**
