### PR TITLE
docs: Improve Examples

### PR DESCRIPTION
**Pull request by cseewald**
I am currently incorporating DB-Scheduler into a project I am working on (10000 onetimetasks processed per hour in an Oracle database). Thanks for your awesome work!! 

I decided to contribute something very modest back.

## Changes

* Removed ExampleHelpers.java: method sleep was unused, method registerShutdownHook is replaced by registerShutdownHook in SchedulerBuilder
* Add missing main method in RecurringTaskMain.java

## Reminders
- [-] Added/ran automated tests
- [-] Update README and/or examples
- [X] Ran `mvn spotless:apply`

---
cc @kagkarlsson

### CODE REVIEW

**Comment by kagkarlsson** [comment]
Excellent! Thank you for contributing! 🙏

**Comment by kagkarlsson** [comment]
Btw this PR might be of interest to you as well. It will introduce explicit LIMIT in the fetch-query for all databases.

https://github.com/kagkarlsson/db-scheduler/pull/371

**Review by kagkarlsson — APPROVED** [review]
Thank you for cleaning up the examples! 🙏

**Comment by cseewald** [comment]
> Btw this PR might be of interest to you as well. It will introduce explicit LIMIT in the fetch-query for all databases.
> 
> #371

Yes, I will probably update when it it is part of a release: To make sure the existing db-scheduler version actually works with many 1000 rows in the task table I did a test with huge task data and many 1000 rows within a highly memory constraint JVM. The `java.sql.Statement#setMaxRows` already seems to do a good enough job to only fetch the limited number of rows from the db. But I guess the explicit LIMIT clause helps with query performance.

**Comment by kagkarlsson** [comment]
🎉 This issue has been resolved in `v13.0.0` ([Release Notes](https://github.com/kagkarlsson/db-scheduler/releases/tag/v13.0.0))

**Pull request merged**
