### PR TITLE
Add overridable clock

### PR DESCRIPTION
**Pull request by qmg-aki**
Hi there,

I had a look at #11 and it seemed quite easy to implement, so I had a go at it.

Aki

### CODE REVIEW

**Comment by kagkarlsson** [comment]
Thanks for the contribution :)

What is your use-case, testing?

**Comment by kagkarlsson** [comment]
I will have a look at the PR.

**Comment by qmg-aki** [comment]
@kagkarlsson Hi, the use case is when running under a test environment an app and we have some tasks scheduled for the far future (days or even months). When we want to test those tasks it is easier to:

* Schedule the task for the future
* Forward the clock of the app at the point of the task execution
* Test that the task has executed correctly

**Comment by kagkarlsson** [comment]
Ok. As I said in the #11 you may have to resort to `Thread.sleep(<pollingInterval>)` to be sure the scheduler have run at the new time. It may be a good idea to instead have a method for triggering the scheduler inline, in the current thread? (It is what I have been doing in the unit-tests)

A general comment though is that I feel configurability that supports unit/integration-testing should get a separate builder-class, so it does not "pollute" that `Scheduler.Builder`

**Comment by qmg-aki** [comment]
@kagkarlsson 

> As I said in the #11 you may have to resort to Thread.sleep(<pollingInterval>)

If I understand correctly this would be due to the polling interval correct? Then that means that we just having to wait for the next polling interval to kick in, then the Scheduler will compare the current (overridden) time with the timestamps of the tasks in the database and should start executing the tasks.

> I feel configurability that supports unit/integration-testing should get a separate builder-class

I have added a separate class as you requested, let me know if it is what you were thinking of.

**Comment by kagkarlsson** [comment]
Yeah, it is because the `pollingInterval`, and because everything happens in threads you do not control in the test. Though, one trick that could be used is to count down a [CountDownLatch](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CountDownLatch.html) in the `ExecutionHandler` of the task you are waiting for, and simply call `.await()` on the latch at the end of the test (with some timeout).

When I have tested similar things in the scheduler unit tests, I have used a sort of inline-version of the Scheduler, where you can manually trigger it to go and execute due executions, and everything is run synchronously in the thread running the unit test. (It also uses a `Clock` that can be changed programatically).

**Comment by kagkarlsson** [comment]
Though I am not a big fan of test-code in the `main` artefact, to avoid having to create a multi-module maven project, how about creating a package `package com.github.kagkarlsson.scheduler.test;` where helpers for testing is put. 

And for starters a class 
`TestHelper` with some method that creates a `TestSchedulerBuilder`, where clock can be set and whatever else is necessary. It could subclass `Scheduler.Builder` is that helps.

**Comment by kagkarlsson** [comment]
I am working on this in the branch `test-helpers`.

**Comment by kagkarlsson** [comment]
Sorry for being a bit opinionated on the matter :)
I have implemented a test-helper in PR #41 which has been merged into master. 

Will close this PR.

**Comment by qmg-aki** [comment]
@kagkarlsson sorry for not getting back to you, I have been away. Good to see you have that feature on master, I'm looking forward to using it on your next release.

**Comment by kagkarlsson** [comment]
Just released `4.1` with this in it. Let me know it is not working according to your needs.

**Pull request closed without merging**
