### PR TITLE
move junit explicitly to the test scope

### PR DESCRIPTION
**Pull request by ystarikovich**

### CODE REVIEW

**Comment by kagkarlsson** [comment]
Oh, good catch. Missed this one. Thanks 👍

**Comment by kagkarlsson** [comment]
Do you need a new release with this asap?

**Comment by ystarikovich** [comment]
Not super urgent right now. I'm also thinking to submit more generic Customizer which we used in our auto configuration on behalf of @poberbichler. What do you think about this enhancement, then Scheduler bean creation should be simplified.

```

import com.github.kagkarlsson.scheduler.SchedulerBuilder;

/**
 * Callback interface that can be used to customize a {@link SchedulerBuilder}
 */
@FunctionalInterface
public interface DbSchedulerCustomizer {
    void customize(SchedulerBuilder schedulerBuilder);
}
```

**Comment by kagkarlsson** [comment]
It was actually released yesterday since I had another fix I needed released.

Will have a look at your suggestion for spring boot

**Comment by kagkarlsson** [comment]
Your suggestion for `DbSchedulerCustomizer` makes sense. There might be a source of confusion since you will be able to override properties from `DbSchedulerProperties`, but if it is mentioned explicitly in the javadoc that should be fine.

Customizer apply probably should be moved to the end of `DbSchedulerAutoConfiguration.schedule(..)` method, so that anything you set in the customizer will have precedence.

**Comment by kagkarlsson** [comment]
Feel free to submit a PR :)

**Pull request merged**
