### PR TITLE
Allow configuration of polling limit

### PR DESCRIPTION
**Pull request by bgooren**
Fixes part of #46

### CODE REVIEW

**Comment by bgooren** [comment]
Was thinking along those lines as well, but it quickly becomes dependent on more variables.

E.g. for 2 schedulers with the same performance, polling interval, thread pool size and uniform jobs, that would work.
But suppose you have fast and slow tasks, fast and slow scheduler instances, different thread pool sizes (I made it dependent on number of available cpus for example), it quickly becomes more complex.

... and then I decided that the user probably knows best. Although a better default could be 2 * thread pool size.

**Comment by kagkarlsson** [comment]
Yes I don't think it will be common that the scheduler will get a long backlog of due executions, but sure, for those few cases it might be helpful to be able to tune the size (though I have a feeling it might be a premature optimization). We can keep the setting if you feel it is helpful to you though

I think we should also change the default to 2 or 3 times nr-of-threads, would you mind adding it to this PR?

**Comment by bgooren** [comment]
I have updated the PR: the builder now handles this, automatically setting the polling limit based on the number of threads, unless the polling limit is manually overriden.
When the number of threads is changed, the polling limit is recalculated.

A caller can also explicitly indicate he wants to use the default polling limit by calling ```builder.defaultPollingLimit()```, although it is the default.

I have added a static int ```POLLING_CONCURRENCY_MULTIPLIER``` (set to 3) which is used to calculate the default polling limit.

Have a look and let me know what you think.

**Comment by bgooren** [comment]
Can you please merge these changes? I would like to test my other PR in production, and would like to do so with a more reasonable polling limit.

**Comment by kagkarlsson** [comment]
👍

**Pull request merged**
